name: Deploy Node.js app to Azure Web App - communix-api

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15EF5AF8FBBC41F2A4663F95BCA95E6D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5B65F586427A4265AB8DFF4B0F43C6DD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D8BF59F20064AD282C95D8E0AACD681 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'communix-api'
          slot-name: 'Production'
          package: ./communix-backend
          app_command: 'node index.js'
