name: Build and deploy Node.js app to Azure Web App - communix-api

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./communix-backend
        run: npm install

      - name: Upload application for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-files
          path: ./communix-backend/index.js  # Upload just the index.js if that's all you need

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download application from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-files

      - name: List files in the downloaded artifact (Debugging step)
        run: ls -R ./backend-files || echo "No files to list"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15EF5AF8FBBC41F2A4663F95BCA95E6D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5B65F586427A4265AB8DFF4B0F43C6DD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D8BF59F20064AD282C95D8E0AACD681 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'communix-api'
          slot-name: 'Production'
          package: ./backend-files/index.js  # Directly point to index.js
